[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32 --log-format defmt"

[env]
DEFMT_LOG="info"

# max ssid: 32 chars
# max password: 64 chars
SSID = "EddieIzzard"
PASSWORD = "would like a tray"
SSID2 = "Why would I commit my wifi credentials?"
PASSWORD2 = "and push it to a public repo?"
STATIC_IP = "1.1.1.1 "
GATEWAY_IP = "1.1.1.1"
HOST_IP = "1.1.1.1"


[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
